name: Manual Workflow Trigger

on:
  push:
    branches:
      - main

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-ver.outputs.version }}   # expose to other jobs
    steps:
      - id: get-ver
        run: echo "version=1.4.2" >> $GITHUB_OUTPUT   # set output

  deploy:
    needs: set-version
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying version ${{ needs.set-version.outputs.version }}"
