name: Manual Workflow Trigger
on:
  push:
    branches:
      - main

jobs:
  learing-outputs:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-var.outputs.version }}
    steps:
      - id: set-var
        run: echo "version=1.1.2" >> $GITHUB_OUTPUT

  deployment:
    runs-on: ubuntu-latest
    needs: learing-outputs
    steps:
      - run: echo " deploying version: ${{ needs.learning-outputs.outputs.version }}"
